# Testing_Stuff

name: unit_test

on:
  push:
    branches: [ master, dev, Refactor ]
  pull_request:
    branches: [ master, dev, Refactor ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Just run main.py ()
        run: |
              python3 main.py ${{ secrets.DISCORD_TOKEN }}